create table currency(
	id int GENERATED BY DEFAULT AS IDENTITY primary key,
	name varchar(50) null,
	rate varchar(50) null
);

create table role_table(
	id int GENERATED BY DEFAULT AS IDENTITY primary key,
	name varchar(20) not null
);

create table user_table(
	id int GENERATED BY DEFAULT AS IDENTITY primary key,
	login varchar(100),
	password varchar(100),
	role_id int,
	foreign key(role_id) references role_table(id)
);

create unique index user_table_login_uindex on user_table (login);

insert into role_table(name) values ('ROLE_ADMIN');
insert into role_table(name) values ('ROLE_USER');

insert into user_table (login, password, role_id) values ('admin','$2a$10$XTmPsA5zRC8WR2Px1HqSH.Gg1EZRPZXPGIwouo8rH6GVis3WGMyWq',1);